server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user1?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 192.168.131.143
    port: 6399
    password: root
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: 1000
      cluster:
        refresh:
          adaptive: true
          period: 2000
    database: 0
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  main:
    allow-circular-references: true
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
